# Chart: https://github.com/opendistro-for-elasticsearch/opendistro-build/tree/master/helm
# Default values: https://github.com/opendistro-for-elasticsearch/opendistro-build/blob/master/helm/opendistro-es/values.yaml

#elasticsearch:
#   master:
#     replicas: 3
#     persistence:
#       storageClass: alt-storage
#       size: 8Gi
#   data:
#     replicas: 3
#     persistence:
#       storageClass: alt-storage
#       size: 30Gi
#   client:
#     replicas: 2


# The following properties should ONLY be
# modified if you are using your own TLS
# certificates rather than having the
# deployment process obtain TLS certificates
# from cert-manager.  Refer to the section
# "Configure TLS without Using cert-manager" in
# the document logging/tls.md for more information
#
# Uncomment the #elasticsearch line at the top
# of this file and all appropriate lines below.
#
#   config:
#     opendistro_security.authcz.admin_dn:
#     - "CN=es-admin,O=cert-manager"
#     opendistro_security.nodes_dn:
#     - "CN=es-transport,O=cert-manager"
