## Sample: contour/host-based-ingress Version: 0.2.2

apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: v4m-alertmanager
spec:
  virtualhost:
    fqdn: alertmanager.host.cluster.example.com
    tls:
      secretName: v4m-ingress-tls-secret
  routes:
    - conditions:
      - prefix: /
      services:
        - name: v4m-alertmanager
          port: 9093
          protocol: tls

