## Sample: contour/path-based-ingress Version: 0.0.1


apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: v4m-alertmanager
spec:
  virtualhost:
    fqdn: alertmanager.host.cluster.example.com
    tls:
      secretName: alertmanager-ingress-tls-secret
  routes:
    - conditions:
      - prefix: /
      services:
        - name: v4m-alertmanager
          port: 9093
          protocol: tls

