## Sample: contour/path-based-ingress Version: 0.0.1


apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: v4m-prometheus
spec:
  virtualhost:
    fqdn: prometheus.host.cluster.example.com
    tls:
      secretName: prometheus-ingress-tls-secret
  routes:
    - conditions:
      - prefix: /
      services:
        - name: v4m-prometheus
          port: 9090
          protocol: tls

