## Sample: contour/host-based-ingress Version: 0.2.1

#
# Grafana
#

grafana:
  # Disable default configuration of NodePort
  service:
    type: ClusterIP
    nodePort: null
  "grafana.ini":
    server:
      domain: host.cluster.example.com
      root_url: https://grafana.host.cluster.example.com
      serve_from_sub_path: false


# This sample does NOT make the Prometheus and Alertmanager accessible by default.
# However, you can make one or both of these web applications
# accessible by uncommenting out the approprate section below.
# To do so, remove the double hash marks (##) from each line in the section.

# Note that Prometheus and Alertmanager applications
# do not include any native authentication mechanism by default, and
# exposing such an application without other restrictions in place
# is insecure.


#
# Prometheus
#

##prometheus:
##  # Disable default configuration of NodePort
##  service:
##    type: ClusterIP
##    nodePort: null
##  prometheusSpec:
##    externalUrl: https://prometheus.host.cluster.example.com
##    alertingEndpoints:
##      - name: v4m-alertmanager
##        port: http-web
##        scheme: https
##        tlsConfig:
##          insecureSkipVerify: true

#
# Alertmanager:
#

##alertmanager:
##  # Disable default configuration of NodePort
##  service:
##    type: ClusterIP
##    nodePort: null
##  alertmanagerSpec:
##    externalUrl: https://alertmanager.host.cluster.example.com
