# Place overrides for the Prometheus Operator Helm Chart Here

# Chart: https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack
# Default values: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml

# Subcharts ued by the Prometheus Operator chart
# Grafana
# https://github.com/grafana/helm-charts/tree/main/charts/grafana
# https://grafana.com/

# Prometheus Node Exporter
# https://github.com/prometheus/node_exporter
# https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-node-exporter

# kube-state-metrics
# https://github.com/kubernetes/kube-state-metrics
# https://github.com/helm/charts/tree/master/stable/kube-state-metrics

# Custom Resource Definitions for the Prometheus Operator
# https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md

# All 'enabled' values default to true. Set the respective 'enabled' value to
# false to disable deployment of that component.

# Setting the 'externalUrl', 'domain' and 'root_url' values is optional, but will
# ensure cross-component (e.g. Grafana->Prometheus) and alert links are correct.

# prometheusOperator:
#   enabled: true

# kubelet:
  # serviceMonitor:
    # Default to use the https-metrics endpoint
    # Depending on your environment, this may require configuration
    # changes to the kubelet.
    # See issue: https://github.com/coreos/prometheus-operator/issues/926
    # https: true

# Use this snippit to change URL, storage, or retention 
# prometheus:
#   enabled: true
#   prometheusSpec:
#     externalUrl: http://host.mycluster.example.com:31090
#     retention: 7d
#     retentionSize: 20GiB
#     storageSpec:
#       volumeClaimTemplate:
#         spec:
#           storageClassName: myCustomStorageClass
#           resources:
#             requests:
#               storage: 25Gi

# alertmanager:
#   enabled:true
#   alertmanagerSpec:
#     externalUrl: http://host.mycluster.example.com:31091
#     storage:
#       volumeClaimTemplate:
#         spec:
#           storageClassName: myCustomStorageClass

# grafana:
#   enabled: true
#   adminPassword: yourSecretPasswordHere
#   "grafana.ini":
#     # Specifying domain and root_url will create the correct links in alert notifications
#     server:
#       domain: host.mycluster.example.com
#       # This value should change to ingress host/port/path if configured
#       root_url: http://host.mycluster.example.com:31100/
#   persistence:
#     storageClassName: myCustomStorageClass

# nodeExporter:
#   enabled: true
