# Chart: https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-pushgateway
# Default values: https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-pushgateway/values.yaml

persistentVolume:
  # enabled: true
  # size: 2Gi
  storageClass: azuredisk-v4m
