image:
  repository: __AIRGAP_REGISTRY__/grafana/grafana
  pullSecrets: __AIRGAP_IMAGE_PULL_SECRET_NAME__
sidecar:
  image:
    registry: __AIRGAP_REGISTRY__
initChownData:
  image:
    repository: __AIRGAP_REGISTRY__/library/busybox

