readinessProbe:
  httpGet:
    scheme: HTTPS
    port: 443
livenessProbe:
  httpGet:
    scheme: HTTPS
    port: 443
extraContainers: |
  # Add square/ghosttunnel TLS proxy
  - name: tls-proxy
    args:
    - server
    - --listen=:443
    - --target=127.0.0.1:3000
    - --key=/cert/tls.key
    - --cert=/cert/tls.crt
    - --disable-authentication
    image: ghostunnel/ghostunnel:v1.7.1
    imagePullPolicy: IfNotPresent
    ports:
    - name: https
      containerPort: 443 
      protocol: TCP
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      privileged: true
      readOnlyRootFilesystem: true
      runAsUser: 0
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /cert
      name: tls-proxy-secret
      readOnly: true
extraContainerVolumes:
- name: tls-proxy-secret
  secret:
    defaultMode: 420
    secretName: v4m-grafana-__TENANT__-tls-secret
service:
  port: 443
  targetPort: 443
sidecar:
  datasources:
    defaultDatasourceEnabled: false
"grafana.ini":
  server:
    # Bind to localhost so https (tls-proxy) is the only way in
    http_addr: 127.0.0.1