apiVersion: v1
kind: Service
metadata:
  name: prometheus-__TENANT__
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: v4m-prometheus-__TENANT__-tls-secret
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/version: 2.44.0
    v4m.sas.com/tenant: __TENANT__
spec:
  ports:
  - name: service
    port: 443
    protocol: TCP
    targetPort: 9191
  selector:
    app.kubernetes.io/name: prometheus
  sessionAffinity: None
  type: ClusterIP