## Helm Chart:     https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-elasticsearch-exporter
## Default values: https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-elasticsearch-exporter/values.yaml

# image:
#  repository: quay.io/prometheuscommunity/elasticsearch-exporter
#  tag: v1.2.1

# es:
##  The env vars ES_USER and ES_PASSWORD are set, by default,
##  based on the K8s secret internal-user-metricgetter
#   uri: https://$(ES_USER):$(ES_PASSWORD)@v4m-es-client-service:9200
