# Chart: https://github.com/opensearch-project/helm-charts/tree/main/charts/opensearch-dashboards
# Default values: https://github.com/opensearch-project/helm-charts/blob/main/charts/opensearch-dashboards/values.yaml

#image:
#  tag: 1.3.1
#  repository: "opensearchproject/opensearch-dashboards"
#  pullPolicy: "IfNotPresent"

## See samples/ingress and/or samples/tls for examples
## of how to configure ingress (host or path based) and
## TLS

