# Chart: https://github.com/opensearch-project/helm-charts/tree/opensearch-dashboards-2.9.0/charts/opensearch-dashboards
# Default values: https://github.com/opensearch-project/helm-charts/blob/opensearch-dashboards-2.9.0/charts/opensearch-dashboards/values.yaml

#image:
#  tag: 2.6.0
#  repository: "opensearchproject/opensearch-dashboards"
#  pullPolicy: "IfNotPresent"

## See samples/tls for examples of how to
## configure TLS+ingress (host or path based)

