persistence:
  storageClass: azuredisk-v4m


## OpenSearch ingress is optional
#ingress:
#  ingressClassName: nginx
#  annotations:
#    nginx.ingress.kubernetes.io/configuration-snippet: |
#      rewrite (?i)/opensearch/(.*) /$1 break;
#      rewrite (?i)/opensearch$ / break;
#    nginx.ingress.kubernetes.io/rewrite-target: /opensearch
#    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
#  enabled: true
#  path: /opensearch
#  pathType: Prefix
#  hosts:
#    - host.cluster.example.com
#  tls:
#    - secretName: elasticsearch-ingress-tls-secret
#      hosts:
#        - host.cluster.example.com

